### ISSUE TITLE
Need advice : where do I put the "give up" button ?

### ISSUE THREAD

**Issue by Th0re** [MrFouss/The-Projects#50]

**Comment by MrFouss** [comment]
I'd say to put it in the middle to the right, just above the actions frame. Or, if you wanna play with the player's nerves, you can put it in the middle of the four buildings. What do you think about it?

**Comment by Ezia** [comment]
I agree with Fouss ;)

**Comment by Th0re** [comment]
Oh yeah just in the middle : "Give up ?"

**Comment by MrFouss** [comment]
Yup yup!
