### ISSUE TITLE
We have a problem of speed

### ISSUE THREAD

**Issue by Th0re** [MrFouss/The-Projects#59]
The controller asks for a lot of things before it can be computed by the view and the model...
You have to find a way to get around that. Putting Platform.runLater(() -> theNeededMethod()); each time there is a problem could work...

**Comment by Ezia** [comment]
I don't understand the problem ... normally, the controller and the view run on 2 different threads.

**Comment by Th0re** [comment]
Yes, but what happen is : thread 1 say to thread 2 : do this method.
thread 2 say : ok ! While thread 2 is doing the method, thread 1 say to thread 2 : now do this method !
thread 2 say : I wish I could do it, however, I didn't finish the first task you gave to me... I know ! Here, take an Exception :) !

**Comment by Ezia** [comment]
I did not put "synchronized" everywhere, that's why ;)
it's not a performance problem.
furthermore, I believe that when the view thread says "do this method", it is itself that executes it in fact. You cannot tell an existing thread "do this".
