### ISSUE TITLE
Card management in view

### ISSUE THREAD

**Issue by Th0re** [MrFouss/The-Projects#60]
I'm going to completely change my card management : 
I'm going to create an enum : 
Owner {
PLAYER_DECK,
PLAYER_DISCARD,
PROJECT_DECK,
PROJECT_DISCARD,
PLAYER1,
PLAYER2,
PLAYER3,
PLAYER4,
HACKER
}
there will be these methods :
void drawCards(Owner actualOwner, Owner newOwner, boolean clickable, ArrayList<String> roomNamesOfRoomCards, ArrayList<Event> eventsOfEventCards, int numberOfPartyCards)
void discardCards() //move cards to their predefined newOwner
void discardCard(Owner newOwner, String roomNameOfRoomCard)
void discardCard(Owner newOwner, Event eventOfEventCard)

Does this seem alright to you ?

**Comment by Ezia** [comment]
ok pour owner
