### ISSUE TITLE
Lack of initial projects ?

### ISSUE THREAD

**Issue by Ezia** [MrFouss/The-Projects#61]
When displaying the game board, it seems that there is only a few projects. Is it normal from a point of view of the model ? Or is it a wrong displaying (projects hidden behind the rooms for example) ? Or maybe I'm just not using the model and the view correctly ^^'

**Comment by MrFouss** [comment]
I think there is an error in the view since I'm okay in the Model. If you wanna make sure, look in the constructor of Model, just before the end of the constructor.

**Comment by Th0re** [comment]
I checked with the debugger the number of displayed projects is equal to the number of time the displayAddProjectToRoom is called.
