### ISSUE TITLE
The group leader is a pain in the a**

### ISSUE THREAD

**Issue by Ezia** [MrFouss/The-Projects#62]
That role is really complicated to handle, what about removing it from the game ?

**Comment by MrFouss** [comment]
As you wish. What does @Th0re think about it?

**Comment by Th0re** [comment]
Well, he is one of the more useful but as you wish...

**Comment by Ezia** [comment]
@Th0re Can you manage pawn clickability ?

**Comment by Th0re** [comment]
I can make a public void setPawnClickable(Role role, boolean clickable) and there already is a firePawnClicked(Role role).

**Comment by Ezia** [comment]
ok nikel ;)
