### ISSUE TITLE
Transform displayMovePawn rooms attribut into anything but a String...rooms

### ISSUE THREAD

**Issue by Ezia** [MrFouss/The-Projects#66]
String...rooms requires to traverse my Collection to create an array and send it to the method, which is kinda useless. Any collection will do since I can create a Collection from any other Collection (easy "cast").

**Comment by Th0re** [comment]
anyCollection.toArray(new String[anyCollection.size()]) works too.

**Comment by Ezia** [comment]
It did not work when I tried

**Comment by Th0re** [comment]
shortP.toArray(new String[shortP.size()]) works.
