### ISSUE TITLE
Is it possible to notify me when an animation is finished ?

### ISSUE THREAD

**Issue by Ezia** [MrFouss/The-Projects#67]
As we experienced, asking for too many animations at the same time either results in an error or simply doesn't work properly.

**Comment by Th0re** [comment]
I'll make a animationFinished() But it would be better if you waited a little longer than the end of the animation so the player have time to read the cards for exemple... Do you want a cleaned() to ?

**Comment by Th0re** [comment]
done.

**Comment by Ezia** [comment]
thx

**Comment by Ezia** [comment]
ah hum, sorry, I realized that it would be easier if every time I call for an animation, you do not return the method as long as the animation is not finished.

**Comment by Ezia** [comment]
I don't know if it's because of our last updates, but the animations freeze
