### ISSUE TITLE
reachable rooms does not work properly when dealing with group leader

### ISSUE THREAD

**Issue by Ezia** [MrFouss/The-Projects#73]
the action points seem to be reduced by 1 for unmoved players when I just moved a pawn with group leader.

**Comment by Ezia** [comment]
Try different things with the group leader to see.

**Comment by Th0re** [comment]
Now if it's not the group leader we can't move any pawn..

**Comment by MrFouss** [comment]
For me, moving with the leader doesn't even work.

**Comment by Ezia** [comment]
It is not very visible, but when you are the group leader and you click the run button, the pawns are set to clickable.

**Comment by MrFouss** [comment]
Fixed.
