### ISSUE TITLE
Do I cancel the Event cards always clickable ?

### ISSUE THREAD

**Issue by Th0re** [MrFouss/The-Projects#74]
As the players are supposed to be able to use them anytime...

**Comment by Ezia** [comment]
hum .... I don't know. when I ask you to display unclickable cards, I'd like them to be unclickables ; if I ask you to make them clackable, I'd like them to be clickable. since I always precise the clickability ...

**Comment by Th0re** [comment]
yes but normally an event card can be played anytime, so do we go against that ?

**Comment by Ezia** [comment]
oh yeah ^^ nothing should be user interactive out of the action phase (but it could if the player likes to toy with the program).
