### ISSUE TITLE
The clickable pawns are not enough visible when the Leader wants to move someone

### ISSUE THREAD

**Issue by MrFouss** [MrFouss/The-Projects#78]
I'd add something else to explain that the Leader has to click on one of the pawns. If @Ezia didn't explain that the pawns were clickable, I'd have kept thinking the Leader's move action was buggy and broken.

**Comment by Th0re** [comment]
Is that enough or do I make a makeAllPawnsClickable() with the blacked screen ?

**Comment by MrFouss** [comment]
With the colors from earlier was better, but with a blacked screen would maybe be the best.

**Comment by Th0re** [comment]
ok !

**Comment by Th0re** [comment]
done.

**Comment by Ezia** [comment]
Looks fine !
